classdef PTEntry
    % PTENTRY structure for each entry of PeriodTable.
    %
    %    See also PeriodTable, ReadUPF, HGH.

    %  Copyright (c) 2022-2023 Hengzhun Chen and Yingzhou Li, 
    %                          Fudan University
    %  This file is distributed under the terms of the MIT License.

    properties (SetAccess = public)
        params
        samples   % Radial grid, pseudocharge and nonlocal projectors and their derivatives.
        cutoffs   % Cutoff value for different samples
        
        NLweights
        NLtypes
    end

    methods
        function PTentry = PTEntry()
            PTentry.params = struct(...
                'Znuc', [], ...
                'Mass', [], ...
                'Zion', [], ...
                'Eself', [], ...
                'RGaussian', [] ...
                );
            PTentry.samples = struct(...
                'rad', [], ...
                'pseudoCharge', [], ...
                'drv_pseudoCharge', [], ...
                'vLocal', [], ...
                'drv_vLocal', [], ...
                'rhoAtom', [], ...
                'drv_rhoAtom', [], ...
                'nonlocal', [] ...
                );
            PTentry.cutoffs = struct(...
                'rad', [], ...
                'pseudoCharge', [], ...
                'drv_pseudoCharge', [], ...
                'vLocal', [], ...
                'drv_vLocal', [], ...
                'rhoAtom', [], ...
                'drv_rhoAtom', [], ...
                'nonlocal', [] ...
                );
        end
    end 
         
end